#!/bin/bash

#SBATCH -p general
#SBATCH -n 2
#SBATCH -N 1
#SBATCH --mem 14000
#SBATCH -t 4-00:00
#SBATCH -J genotypeGVCF
#SBATCH -o /n/regal/haig_lab/mhelmore/alignment_array/GATK/logs/genotypeGVCF_12-1-17_%j.out
#SBATCH -e /n/regal/haig_lab/mhelmore/alignment_array/GATK/logs/genotypeGVCF_12-1-17_%j.err
#SBATCH --mail-user=m.holly.elmore@gmail.com # Email to which notifications will be sentcd log

module load java/1.8.0_45-fasrc01
module load jdk/1.8.0_45-fasrc01
 
java -Xmx12g -XX:ParallelGCThreads=1 -jar ~/sw/GenomeAnalysisTK.jar \
-T GenotypeGVCFs \
-R /n/home15/elmoremh/haig_lab_elmoremh/FINAL_ASSEMBLIES/10511_Aphal_PT_AllpathsLG.LINKS.jelly.pilon.fa \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10004.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10007.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10016.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10018.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10019.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10169.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10170.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10171.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10175.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10221.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10222.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10223.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10224.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10225.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10226.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10227.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10228.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10229.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10230.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10231.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10232.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10233.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10237.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10238.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10239.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10240.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10241.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10277.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10280.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10281.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10282.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10283.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10287.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10288.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10292.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10293.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10294.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10295.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10298.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10299.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10300.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10301.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10303.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10304.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10306.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10309.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10326.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10327.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10328.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10329.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10330.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10331.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10334.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10347.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10348.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10349.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10350.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10354.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10355.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10356.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10380.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10384.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10502.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10503.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10504.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10505.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10506.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10508.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10509.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10510.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10511.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10512.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10513.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10707.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10708.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10709.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10710.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10711.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10712.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10713.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10715.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10716.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10717.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10718.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10719.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10720.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10721.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10801.raw_variants.g.vcf \
--variant /n/regal/haig_lab/mhelmore/alignment_array/GATK/gvcf/10802.raw_variants.g.vcf \
-o /n/regal/haig_lab/mhelmore/alignment_array/GATK/vcf/joint_calls_12-1-17vcf/